### ISSUE TITLE
Maintaining as a fork

### ISSUE THREAD

**Issue by shevek** [JogAmp/jcpp#1]
If there's any way you can maintain this as a fork rather than a copy, I'd really the ability to easily adopt your improvements into mainline.

Not a requirement by any means, of course, but there are several features which a few subcommunities need, especially bindings-generators, and I want to support you all as best I can.

:-)

S.

**Comment by sgothel** [comment]
You probably 'only' mention the github state, i.e. I populated it from my local machine - not via 'github fork'.
However, this jcpp git instance is-a fork, i.e. a branch, of your work - of course. 
It is mentioned in the headline/description as well.

You should be able to send my git pull requests via email .. hmm.
For example, I track your changes in my local git repo .. and can merge, sure.

I could not find an easy way to change the github state, i.e. that it is a fork of your work.
If you find a way - let me know.
